CREATE TABLE short_urls (
  shortUrl VARCHAR(50) PRIMARY KEY,
  longUrl VARCHAR(2048) NOT NULL,
  expiresAt TIMESTAMP,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE click_events (
  clickId SERIAL UNIQUE NOT NULL,
  shortUrl VARCHAR(50) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (shortUrl) REFERENCES short_urls(shortUrl)
);
